### ISSUE TITLE
Notification 

### ISSUE THREAD

**Issue by mirmibrahim** [ozbek/al-muazzin#4]
Suppose i have set adhan notification from notification dialog for zuhur . Zuhur time is 11:59 am 
when the time arrives at 11:59 am the adhan and notification is generated . I clear the notifcation from notification bar then when i open the app , the notification again generates with azan, I again exit the app and kill the app then reopen the app , then again adhan and notification is generated . This keeps repeating till 3 minutes , I want to stop this behaviour , Please help

**Comment by ozbek** [comment]
Which version are you using? Or are you building from sources?

**Comment by mirmibrahim** [comment]
i am building from your github code

**Comment by mirmibrahim** [comment]
Help man i am stucked in it

**Comment by ozbek** [comment]
Please be patient as this seems to be related with API changes and is going to take time to pinpoint the problem.

**Comment by mirmibrahim** [comment]
ok i am waiting for it

**Comment by ozbek** [comment]
@mirmibrahim, please test and let me know if the problem still persists.
